[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://appointment-scheduler-api.netlify.app/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 