[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://appointment-scheduler-backend-duvy.onrender.com/api"

[context.production]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[context.production.environment]
  VITE_API_URL = "https://appointment-scheduler-backend-duvy.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/appointments/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/calendar"
  to = "/index.html"
  status = 200
  force = true 