[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://appointment-scheduler-api.netlify.app/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 